import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

// Demostración: podemos hacer un POST en lugar de un GET en un iframe mediante la implementación
// de un formulario. De esta manera evitamos que el token viaje en la URL.

// La siguiente prueba sería hacer el form usando javascript para evitar que el token pueda ser interceptado
// en el HTML y además para no hacer un form con HTLM ya que no es la idea que el usuario tenga que hacer click
// en un botón para obtener la data

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form action="/api/show-card-data" method="POST" target="my_iframe">
          <input inputMode="numeric" id="token" name="token" />

          <input type="submit" />
        </form>
        <iframe name="my_iframe" src="about:blank"></iframe>
      </main>
    </>
  );
}
